workflows:
  version: 2
  build:
    jobs:
      - build

version: 2
jobs:
  build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - restore_cache:
        key: cache1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run
        name: Install Python deps in a venv
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - save_cache:
          key: cache1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
