version: 2
workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build ECS image
          command: |
            export AWS_ACCESS_KEY_ID=AKIATPFT5MTK43CXSNPK
            export AWS_SECRET_ACCESS_KEY=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
            export AWS_DEFAULT_REGION=us-east-1
            export AWS_REPO_ACCOUNT=238748001493.dkr.ecr.us-east-1.amazonaws.com
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_REPO_ACCOUNT
            docker build -t swapi-chall
            docker tag swapi-chall $AWS_REPO_ACCOUNT/swapi-chall:latest
            docker push 238748001493.dkr.ecr.us-east-1.amazonaws.com/swapi-chall:latest




