name: Test Dispatch

on:
  repository_dispatch:
    types: echo-test
    
env: 
  environment: ${{ github.event.client_payload.environment }}

jobs:
  build-dev:
    if: ${{ env.environment == 'dev' }} 
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test dev"
  build-stg:
    if: ${{ env.environment == 'stg' }} 
    name: Deploy stg
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test stg"
