name: Main dispatch

on:
  repository_dispatch:
    types: deploy-components

jobs:
  build-dev:
    if: ${{ github.event.client_payload.environment == 'dev' }} 
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the develop branch
        uses: actions/checkout@v3.3.0
        with:
          ref: 'develop'
      - name: Download components
        run: sh download-components.sh
      - name: Running the update script
        run: sh update-develop.sh feature-${{github.event.client_payload.component_name}} arq-actions2.txt
  build-stg:
    if: ${{ github.event.client_payload.environment == 'stg' }} 
    name: Deploy stg
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test stg"
  build-prd:
    if: ${{ github.event.client_payload.environment == 'prd' }} 
    name: Deploy prd
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test prd"
