name: Test Dispatch

on:
  repository_dispatch:
    types: echo-test
    
env: 
  environment: "dev"

jobs:
  build-dev:
    if: $environment == "dev"
    name: Deploy dev
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test dev"
  build-stg:
    if: $environment == "stg"
    name: Deploy stg
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "test stg"
